import { NodeMeta, Connection } from '../../types/node.types';
import { CATEGORY_PHYSICS } from '../../physics/bodies';

export const INITIAL_DEMO_NODES: NodeMeta[] = [
  {
    id: 'ns-hub',
    title: '🪐 NothingSense Ecosistema',
    content: '# NothingSense Hub\nCentro neurálgico de productos y software:\n- **Software & PKM:** [[GaviNote]], [[DecodificaTuDocumento]], [[Boda ZJ]].\n- **EdTech:** [[Matkii LMS]], [[Tallerizador]], [[Local RAG Service]].\n- **IA & Asistentes:** [[NoSe Brain]], [[Valiant Borg Automation]].\n- **Hardware & IoT:** [[Vape Detector ESP32]], [[ESP32 Sensor Suite]].\n- **Mobile & Gaming:** [[NAP Marketplace]], [[Capacitor Mobile]], [[Empire Tycoon]], [[La Matria MC Server]].',
    tags: ['nothingsense', 'ecosistema', 'hub', 'arquitectura'],
    category: 'central',
    initialX: 0,
    initialY: 0,
    width: CATEGORY_PHYSICS.central.width + 50,
    height: CATEGORY_PHYSICS.central.height + 60,
    createdAt: Date.now(),
    isPinned: true,
  },
  {
    id: 'ns-gavinote',
    title: 'GaviNote',
    content: '## Segundo Cerebro Espacial\n- [x] Motor de física Matter.js con gravedad cero e inercia.\n- [x] Enlaces bidireccionales [[Wikilinks]] en tiempo real.\n- [x] Quick Switcher (Ctrl+K) y Bóveda Local privada aislada de Git.\n- [ ] Síntesis semántica automática con [[NoSe Brain]] y [[Local RAG Service]].',
    tags: ['gavinote', 'pkm', 'second-brain', 'nextjs', 'matterjs'],
    category: 'idea',
    initialX: -340,
    initialY: -160,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 1000,
  },
  {
    id: 'ns-matkii',
    title: 'Matkii LMS',
    content: '## Plataforma EdTech de Ciencias Exactas\n- Evaluación adaptativa con doble aleatorización.\n- Fórmulas matemáticas KaTeX y métodos paso a paso.\n- Cifrado PII a nivel de base de datos.\n- Empaquetado nativo con [[Capacitor Mobile]].\n- Banco de talleres generado por [[Tallerizador]].',
    tags: ['matkii', 'edtech', 'nextjs', 'prisma', 'postgresql', 'katex'],
    category: 'central',
    initialX: 360,
    initialY: -180,
    width: CATEGORY_PHYSICS.central.width + 20,
    height: CATEGORY_PHYSICS.central.height + 20,
    createdAt: Date.now() - 2000,
  },
  {
    id: 'ns-nose',
    title: 'NoSe Brain',
    content: '## Asistente Jarvis Local (Python)\n- Reconocimiento de voz offline con Vosk (Wake word: "NoSe").\n- Personalidad caribeña vallenata (Valledupar).\n- Inferencia distribuida multi-nodo con Ollama.\n- Auditoría de seguridad y escaneo de red local.\n- Enlazado con [[NothingSense Ecosistema]] y [[GaviNote]].',
    tags: ['nose', 'ia-local', 'python', 'vosk', 'ollama', 'seguridad'],
    category: 'referencia',
    initialX: -380,
    initialY: 160,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 3000,
  },
  {
    id: 'ns-tallerizador',
    title: 'Tallerizador',
    content: '## Generador Pedagógico Inteligente\n- Generación de guías de trabajo y evaluaciones alineadas a DBA Colombia.\n- Utiliza [[Local RAG Service]] para estructurar problemas matemáticos.\n- Exportación directa para el banco de [[Matkii LMS]].',
    tags: ['tallerizador', 'edtech', 'react', 'vite', 'rag'],
    category: 'tarea',
    initialX: 380,
    initialY: 160,
    width: CATEGORY_PHYSICS.tarea.width + 20,
    height: CATEGORY_PHYSICS.tarea.height + 20,
    createdAt: Date.now() - 4000,
  },
  {
    id: 'ns-wao',
    title: 'DecodificaTuDocumento',
    content: '## Traductor IA de Documentos Complejos (wao)\nConvierte recibos médicos, cartas de desalojo y contratos en explicaciones claras + próximos pasos accionables.\n- Arquitectura serverless con Cloudflare Pages y Stripe.\n- Integrado con la visión de [[NothingSense Ecosistema]].',
    tags: ['wao', 'ia', 'documentos', 'stripe', 'cloudflare'],
    category: 'idea',
    initialX: -180,
    initialY: 340,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 5000,
  },
  {
    id: 'ns-nap-market',
    title: 'NAP Marketplace',
    content: '## Plataforma de Servicios y Empleos\nMarketplace de dos lados para conectar oferta y demanda laboral.\n- [x] Cliente multiplataforma en Flutter y [[Capacitor Mobile]].\n- [x] Backend serverless en Firebase Cloud Functions y Firestore.\n- [ ] Integración de pasarelas de pago con Nequi y MercadoPago.',
    tags: ['nap', 'marketplace', 'flutter', 'firebase', 'mobile'],
    category: 'tarea',
    initialX: 180,
    initialY: 340,
    width: CATEGORY_PHYSICS.tarea.width + 20,
    height: CATEGORY_PHYSICS.tarea.height + 20,
    createdAt: Date.now() - 6000,
  },
  {
    id: 'ns-bodazj',
    title: 'Boda Z&J',
    content: '## Plataforma Integral de Eventos\n- RSVP dinámico con token único para invitados.\n- Muro de Gala en vivo con moderación y slideshow para proyector.\n- Integración musical en tiempo real con Spotify API.\n- Parte de [[NothingSense Ecosistema]].',
    tags: ['bodazj', 'eventos', 'nextjs', 'prisma', 'spotify'],
    category: 'referencia',
    initialX: 0,
    initialY: -360,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 7000,
  },
  {
    id: 'ns-vapdetector',
    title: 'Vape Detector ESP32',
    content: '## Sensor IoT de Detección de Aerosoles\n- Firmware C++ en PlatformIO para microcontrolador ESP32.\n- Sensores ópticos y de partículas para detección en tiempo real.\n- Dashboard de monitoreo en PC y alertas instantáneas.\n- Comparte arquitectura con [[ESP32 Sensor Suite]].',
    tags: ['iot', 'esp32', 'hardware', 'c++', 'platformio', 'sensores'],
    category: 'alerta',
    initialX: -540,
    initialY: -40,
    width: CATEGORY_PHYSICS.alerta.width + 20,
    height: CATEGORY_PHYSICS.alerta.height + 20,
    createdAt: Date.now() - 8000,
  },
  {
    id: 'ns-esp32',
    title: 'ESP32 Sensor Suite',
    content: '## Sistema Satelital de Sensores y Telemetría\n- Red de sensores distribuidos con firmware PlatformIO.\n- Comunicación por WiFi/BLE y estación central con dashboard.\n- Diseñado para integración con [[Vape Detector ESP32]] y [[NoSe Brain]].',
    tags: ['esp32', 'hardware', 'embedded', 'telemetria', 'iot'],
    category: 'referencia',
    initialX: -560,
    initialY: -220,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 9000,
  },
  {
    id: 'ns-juego',
    title: 'Empire Tycoon',
    content: '## Videojuego de Estrategia y Gestión\n- Construcción y gestión económica en HTML5 Canvas.\n- Empaquetado APK para Android mediante [[Capacitor Mobile]].\n- Sistema de guardado y progresión offline.',
    tags: ['game', 'tycoon', 'javascript', 'capacitor', 'android'],
    category: 'idea',
    initialX: 540,
    initialY: -320,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 10000,
  },
  {
    id: 'ns-minecraft',
    title: 'La Matria MC Server',
    content: '## Servidor de Minecraft & Automatización\n- Servidor optimizado Paper/Spigot con plugins personalizados.\n- Resource Pack dedicado con plantillas de texturas.\n- Scripts de sincronización SFTP, RCON y backups automáticos.',
    tags: ['minecraft', 'server', 'paper', 'python', 'sftp', 'gaming'],
    category: 'referencia',
    initialX: 560,
    initialY: -120,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 11000,
  },
  {
    id: 'ns-valiant',
    title: 'Valiant Borg Automation',
    content: '## Herramienta de Automatización de Escritorio\n- Aplicación gráfica de automatización y control en Python.\n- Empaquetado standalone con PyInstaller.\n- Complemento de productividad para [[NoSe Brain]].',
    tags: ['automation', 'python', 'desktop', 'tools'],
    category: 'tarea',
    initialX: -520,
    initialY: 300,
    width: CATEGORY_PHYSICS.tarea.width + 20,
    height: CATEGORY_PHYSICS.tarea.height + 20,
    createdAt: Date.now() - 12000,
  },
  {
    id: 'ns-rag',
    title: 'Local RAG Service',
    content: '## Motor RAG & Recuperación Aumentada\nIndexación semántica y recuperación de conocimiento local para:\n- [[Tallerizador]]: Generación de problemas y talleres.\n- [[DecodificaTuDocumento]]: Extracción de cláusulas legales.\n- [[GaviNote]]: Búsqueda semántica en el Segundo Cerebro.',
    tags: ['rag', 'ia', 'embeddings', 'semantic-search'],
    category: 'referencia',
    initialX: 540,
    initialY: 60,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 13000,
  },
  {
    id: 'ns-capacitor',
    title: 'Capacitor Mobile',
    content: '## Ecosistema Móvil Nativo\nEstrategia híbrida para compilar aplicaciones web en APK nativos de Android:\n- [[Matkii LMS]]: Experiencia K-12 móvil offline.\n- [[NAP Marketplace]]: Acceso nativo para trabajadores.\n- [[Empire Tycoon]]: Videojuego móvil.',
    tags: ['capacitor', 'android', 'ios', 'mobile', 'pwa'],
    category: 'idea',
    initialX: 280,
    initialY: -360,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 14000,
  },
];

export const INITIAL_DEMO_CONNECTIONS: Connection[] = [
  // Conexiones principales desde NothingSense Hub
  { id: 'conn-hub-gavinote', sourceId: 'ns-hub', targetId: 'ns-gavinote', type: 'apoyo', label: 'segundo cerebro' },
  { id: 'conn-hub-matkii', sourceId: 'ns-hub', targetId: 'ns-matkii', type: 'apoyo', label: 'lms edtech' },
  { id: 'conn-hub-nose', sourceId: 'ns-hub', targetId: 'ns-nose', type: 'apoyo', label: 'asistente local' },
  { id: 'conn-hub-taller', sourceId: 'ns-hub', targetId: 'ns-tallerizador', type: 'apoyo', label: 'generador' },
  { id: 'conn-hub-wao', sourceId: 'ns-hub', targetId: 'ns-wao', type: 'neutra', label: 'ia documentos' },
  { id: 'conn-hub-nap', sourceId: 'ns-hub', targetId: 'ns-nap-market', type: 'neutra', label: 'marketplace' },
  { id: 'conn-hub-boda', sourceId: 'ns-hub', targetId: 'ns-bodazj', type: 'neutra', label: 'eventos' },
  { id: 'conn-hub-vap', sourceId: 'ns-hub', targetId: 'ns-vapdetector', type: 'conflicto', label: 'alerta iot' },
  { id: 'conn-hub-juego', sourceId: 'ns-hub', targetId: 'ns-juego', type: 'neutra', label: 'videojuego' },

  // Hardware & IoT
  { id: 'conn-vap-esp32', sourceId: 'ns-vapdetector', targetId: 'ns-esp32', type: 'apoyo', label: 'firmware base' },
  { id: 'conn-nose-valiant', sourceId: 'ns-nose', targetId: 'ns-valiant', type: 'apoyo', label: 'automatizacion' },

  // EdTech & IA
  { id: 'conn-matkii-taller', sourceId: 'ns-matkii', targetId: 'ns-tallerizador', type: 'apoyo', label: 'curriculo dba' },
  { id: 'conn-taller-rag', sourceId: 'ns-tallerizador', targetId: 'ns-rag', type: 'apoyo', label: 'recuperacion' },
  { id: 'conn-wao-rag', sourceId: 'ns-wao', targetId: 'ns-rag', type: 'neutra', label: 'extraccion' },
  { id: 'conn-nose-gavinote', sourceId: 'ns-nose', targetId: 'ns-gavinote', type: 'apoyo', label: 'sintesis' },

  // Mobile & Capacitor
  { id: 'conn-matkii-capacitor', sourceId: 'ns-matkii', targetId: 'ns-capacitor', type: 'apoyo', label: 'apk android' },
  { id: 'conn-nap-capacitor', sourceId: 'ns-nap-market', targetId: 'ns-capacitor', type: 'neutra', label: 'mobile client' },
  { id: 'conn-juego-capacitor', sourceId: 'ns-juego', targetId: 'ns-capacitor', type: 'neutra', label: 'android build' },
  { id: 'conn-juego-mc', sourceId: 'ns-juego', targetId: 'ns-minecraft', type: 'neutra', label: 'gaming stack' },
];
