import { NodeMeta, Connection } from '../../types/node.types';
import { CATEGORY_PHYSICS } from '../../physics/bodies';

export const INITIAL_DEMO_NODES: NodeMeta[] = [
  {
    id: 'ns-hub',
    title: '🪐 NothingSense Ecosistema',
    content: 'Centro neurálgico de proyectos tecnológicos:\n- [[GaviNote]]: Segundo cerebro espacial con física 2D.\n- [[Matkii LMS]]: Plataforma educativa adaptativa para ciencias exactas.\n- [[NoSe Brain]]: Asistente Jarvis local auto-evolutivo.\n- [[Tallerizador]]: Generador de talleres con [[Local RAG Service]].\n- [[DecodificaTuDocumento]]: Traductor IA de documentos de alto estrés.\n- [[NAP Marketplace]]: Plataforma de empleo y servicios.\n- [[Boda ZJ]]: Plataforma interactiva de eventos.',
    tags: ['nothingsense', 'ecosistema', 'hub', 'arquitectura'],
    category: 'central',
    initialX: 0,
    initialY: 0,
    width: CATEGORY_PHYSICS.central.width + 40,
    height: CATEGORY_PHYSICS.central.height + 40,
    createdAt: Date.now(),
    isPinned: true,
  },
  {
    id: 'ns-gavinote',
    title: 'GaviNote',
    content: '## Segundo Cerebro Espacial\n- [x] Motor de física Matter.js con gravedad cero e inercia.\n- [x] Enlaces bidireccionales [[Wikilinks]] en tiempo real.\n- [x] Quick Switcher (Ctrl+K) y Bóveda Local privada aislada de Git.\n- [ ] Integración con [[NoSe Brain]] para síntesis semántica.',
    tags: ['gavinote', 'pkm', 'second-brain', 'nextjs', 'matterjs'],
    category: 'idea',
    initialX: -320,
    initialY: -180,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 1000,
  },
  {
    id: 'ns-matkii',
    title: 'Matkii LMS',
    content: '## Plataforma EdTech de Ciencias Exactas\n- Sistema de evaluación adaptativa con doble aleatorización.\n- Fórmulas en notación KaTeX y métodos paso a paso.\n- Cifrado PII a nivel de base de datos.\n- Empaquetado nativo con [[Capacitor Mobile]].\n- Alimentado por recursos de [[Tallerizador]].',
    tags: ['matkii', 'edtech', 'nextjs', 'prisma', 'postgresql', 'katex'],
    category: 'central',
    initialX: 340,
    initialY: -180,
    width: CATEGORY_PHYSICS.central.width + 20,
    height: CATEGORY_PHYSICS.central.height + 20,
    createdAt: Date.now() - 2000,
  },
  {
    id: 'ns-nose',
    title: 'NoSe Brain',
    content: '## Asistente Jarvis Local (Python)\n- Reconocimiento de voz offline con Vosk (Wake word: "NoSe").\n- Personalidad caribeña vallenata (Valledupar).\n- Inferencia distribuida multi-nodo con Ollama.\n- Auditoría de seguridad y escaneo de puertos en red local.\n- Conexión con [[NothingSense Ecosistema]].',
    tags: ['nose', 'ia-local', 'python', 'vosk', 'ollama', 'seguridad'],
    category: 'referencia',
    initialX: -360,
    initialY: 180,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 3000,
  },
  {
    id: 'ns-tallerizador',
    title: 'Tallerizador',
    content: '## Generador Pedagógico Inteligente\n- Generación de guías de trabajo y evaluaciones alineadas a DBA Colombia.\n- Utiliza [[Local RAG Service]] para estructurar problemas matemáticos.\n- Compatible con el banco curricular de [[Matkii LMS]].',
    tags: ['tallerizador', 'edtech', 'react', 'vite', 'rag'],
    category: 'tarea',
    initialX: 360,
    initialY: 180,
    width: CATEGORY_PHYSICS.tarea.width + 20,
    height: CATEGORY_PHYSICS.tarea.height + 20,
    createdAt: Date.now() - 4000,
  },
  {
    id: 'ns-wao',
    title: 'DecodificaTuDocumento',
    content: '## Traductor IA de Documentos Complejos (wao)\nConvierte recibos médicos, cartas de desalojo y ofertas de trabajo en lenguaje claro + próximos pasos accionables.\n- Arquitectura por capas con Stripe Checkout.\n- Enlazado a la suite de [[NothingSense Ecosistema]].',
    tags: ['wao', 'ia', 'documentos', 'stripe', 'cloudflare'],
    category: 'idea',
    initialX: -160,
    initialY: 340,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 5000,
  },
  {
    id: 'ns-nap-market',
    title: 'NAP Marketplace',
    content: '## Plataforma de Servicios y Empleos\nMarketplace de dos lados para conectar oferta y demanda laboral.\n- [x] Cliente multiplataforma en Flutter y [[Capacitor Mobile]].\n- [x] Backend serverless en Firebase Cloud Functions.\n- [ ] Pasarela de pagos con Nequi y MercadoPago.',
    tags: ['nap', 'marketplace', 'flutter', 'firebase', 'mobile'],
    category: 'tarea',
    initialX: 180,
    initialY: 340,
    width: CATEGORY_PHYSICS.tarea.width + 20,
    height: CATEGORY_PHYSICS.tarea.height + 20,
    createdAt: Date.now() - 6000,
  },
  {
    id: 'ns-bodazj',
    title: 'Boda ZJ',
    content: '## Plataforma Integral de Eventos\n- RSVP dinámico con token único para invitados.\n- Muro de Gala en vivo con moderación y slideshow.\n- Integración musical con Spotify API y YouTube Music.\n- Parte de la cartera de [[NothingSense Ecosistema]].',
    tags: ['bodazj', 'eventos', 'nextjs', 'prisma', 'spotify'],
    category: 'referencia',
    initialX: 0,
    initialY: -340,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 7000,
  },
  {
    id: 'ns-rag',
    title: 'Local RAG Service',
    content: '## Motor RAG & Búsqueda Semántica\nIndexación semántica y recuperación aumentada para:\n- [[Tallerizador]]: Generación de problemas y talleres.\n- [[DecodificaTuDocumento]]: Extracción de cláusulas legales.\n- [[GaviNote]]: Búsqueda y relaciones en el Segundo Cerebro.',
    tags: ['rag', 'ia', 'embeddings', 'semantic-search'],
    category: 'referencia',
    initialX: 520,
    initialY: 0,
    width: CATEGORY_PHYSICS.referencia.width + 20,
    height: CATEGORY_PHYSICS.referencia.height + 20,
    createdAt: Date.now() - 8000,
  },
  {
    id: 'ns-capacitor',
    title: 'Capacitor Mobile',
    content: '## Ecosistema Móvil Nativo\nEstrategia híbrida para empaquetar aplicaciones web en APK/AAB nativos para Android e iOS:\n- [[Matkii LMS]]: Experiencia K-12 móvil offline.\n- [[NAP Marketplace]]: Acceso nativo para trabajadores y clientes.',
    tags: ['capacitor', 'android', 'ios', 'mobile', 'pwa'],
    category: 'idea',
    initialX: 280,
    initialY: -340,
    width: CATEGORY_PHYSICS.idea.width + 20,
    height: CATEGORY_PHYSICS.idea.height + 20,
    createdAt: Date.now() - 9000,
  },
];

export const INITIAL_DEMO_CONNECTIONS: Connection[] = [
  // Conexiones principales desde NothingSense Hub
  { id: 'conn-hub-gavinote', sourceId: 'ns-hub', targetId: 'ns-gavinote', type: 'apoyo', label: 'segundo cerebro' },
  { id: 'conn-hub-matkii', sourceId: 'ns-hub', targetId: 'ns-matkii', type: 'apoyo', label: 'lms edtech' },
  { id: 'conn-hub-nose', sourceId: 'ns-hub', targetId: 'ns-nose', type: 'apoyo', label: 'asistente local' },
  { id: 'conn-hub-taller', sourceId: 'ns-hub', targetId: 'ns-tallerizador', type: 'apoyo', label: 'generador' },
  { id: 'conn-hub-wao', sourceId: 'ns-hub', targetId: 'ns-wao', type: 'neutra', label: 'ia documentos' },
  { id: 'conn-hub-nap', sourceId: 'ns-hub', targetId: 'ns-nap-market', type: 'neutra', label: 'marketplace' },
  { id: 'conn-hub-boda', sourceId: 'ns-hub', targetId: 'ns-bodazj', type: 'neutra', label: 'eventos' },

  // Relaciones cruzadas entre proyectos
  { id: 'conn-matkii-taller', sourceId: 'ns-matkii', targetId: 'ns-tallerizador', type: 'apoyo', label: 'curriculo dba' },
  { id: 'conn-taller-rag', sourceId: 'ns-tallerizador', targetId: 'ns-rag', type: 'apoyo', label: 'recuperacion' },
  { id: 'conn-matkii-capacitor', sourceId: 'ns-matkii', targetId: 'ns-capacitor', type: 'apoyo', label: 'apk android' },
  { id: 'conn-nap-capacitor', sourceId: 'ns-nap-market', targetId: 'ns-capacitor', type: 'neutra', label: 'mobile client' },
  { id: 'conn-nose-gavinote', sourceId: 'ns-nose', targetId: 'ns-gavinote', type: 'apoyo', label: 'sintesis' },
  { id: 'conn-wao-rag', sourceId: 'ns-wao', targetId: 'ns-rag', type: 'neutra', label: 'extraccion' },
];
